#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

require_once  './UploadCommand.php';
require_once  './CreateListCommand.php';

$application = new Application();

$application->add(new UploadCommand());
$application->add(new CreateListCommand());

$application->run();
